export declare const lightColors: {
    readonly '--aurora-primary-50': "#eff6ff";
    readonly '--aurora-primary-100': "#dbeafe";
    readonly '--aurora-primary-200': "#bfdbfe";
    readonly '--aurora-primary-300': "#93c5fd";
    readonly '--aurora-primary-400': "#60a5fa";
    readonly '--aurora-primary-500': "#3b82f6";
    readonly '--aurora-primary-600': "#2563eb";
    readonly '--aurora-primary-700': "#1d4ed8";
    readonly '--aurora-primary-800': "#1e40af";
    readonly '--aurora-primary-900': "#1e3a8a";
    readonly '--aurora-secondary-50': "#f8fafc";
    readonly '--aurora-secondary-100': "#f1f5f9";
    readonly '--aurora-secondary-500': "#64748b";
    readonly '--aurora-secondary-600': "#475569";
    readonly '--aurora-secondary-700': "#334155";
    readonly '--aurora-success': "#22c55e";
    readonly '--aurora-danger': "#ef4444";
    readonly '--aurora-warning': "#f59e0b";
    readonly '--aurora-background': "#ffffff";
    readonly '--aurora-foreground': "#0f172a";
    readonly '--aurora-muted': "#f1f5f9";
    readonly '--aurora-muted-foreground': "#64748b";
    readonly '--aurora-border': "#e2e8f0";
};
export declare const darkColors: {
    readonly '--aurora-primary-50': "#1e3a8a";
    readonly '--aurora-primary-100': "#1e40af";
    readonly '--aurora-primary-200': "#1d4ed8";
    readonly '--aurora-primary-300': "#2563eb";
    readonly '--aurora-primary-400': "#3b82f6";
    readonly '--aurora-primary-500': "#60a5fa";
    readonly '--aurora-primary-600': "#93c5fd";
    readonly '--aurora-primary-700': "#bfdbfe";
    readonly '--aurora-primary-800': "#dbeafe";
    readonly '--aurora-primary-900': "#eff6ff";
    readonly '--aurora-secondary-50': "#0f172a";
    readonly '--aurora-secondary-100': "#1e293b";
    readonly '--aurora-secondary-500': "#94a3b8";
    readonly '--aurora-secondary-600': "#cbd5e1";
    readonly '--aurora-secondary-700': "#e2e8f0";
    readonly '--aurora-success': "#22c55e";
    readonly '--aurora-danger': "#ef4444";
    readonly '--aurora-warning': "#f59e0b";
    readonly '--aurora-background': "#0f172a";
    readonly '--aurora-foreground': "#f8fafc";
    readonly '--aurora-muted': "#1e293b";
    readonly '--aurora-muted-foreground': "#94a3b8";
    readonly '--aurora-border': "#334155";
};
export type ThemeColors = typeof lightColors;
